### ISSUE TITLE
App crashing when background is set to animation.

### ISSUE THREAD

**Issue by Aniket204** [deepak786/InstagramLikeColorTransition#2]
When textview and some imageview and text is put on top it,it crashes

**Comment by deepak786** [comment]
Hi Aniket,

Can you please share your source code?

**Comment by Aniket204** [comment]
[Attendance_Final.zip](https://github.com/deepak786/InstagramLikeColorTransition/files/2459461/Attendance_Final.zip)

**Comment by deepak786** [comment]
Hi Aniket,
I just run the code and it crashed on Activity `activity_animation.java`. right?

The issue is not with the Library, your activity has a layout named `activity_main.xml` which is used in Activity `activity_animation.java`. But this layout doesn't contain the id `container`.

`LinearLayout container = (LinearLayout) findViewById(R.id.container);`

So the above line or container is **null**, thats why the app crashes.

**Solution 1:**
1. Change your `ConstraintLayout` to `LinearLayout`.
2. Give this layout a id `android:id="@+id/container"`
3. Add background to this layout `android:background="@drawable/animation_list"`.

Here is the complete APP source code which is running
[Attendance_Final (Deepak).zip](https://github.com/deepak786/InstagramLikeColorTransition/files/2461066/Attendance_Final.Deepak.zip)

**Solution 2**
If you want to use the `ConstraintLayout` as the root element
[Attendance_Final (Deepak_ConstraintLayout).zip](https://github.com/deepak786/InstagramLikeColorTransition/files/2461092/Attendance_Final.Deepak_ConstraintLayout.zip)
